captcha_handler:
    path: /captcha-handler
    controller: Captcha\Bundle\CaptchaBundle\Controller\CaptchaHandlerController::indexAction
    methods: [GET]

simple_captcha_handler:
    path: /simple-captcha-handler
    controller: Captcha\Bundle\CaptchaBundle\Controller\SimpleCaptchaHandlerController::indexAction
    methods: [GET]
